hello.c
const struct option longopts[][]
hello.c print a greeting message and exit.Copyright 1992-2017 Free Software Foundation, Inc.This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.You should have received a copy of the GNU General Public License along with this program. If not, see https://www.gnu.org/licenses/.Структура ключей и их символьных значений
static _Noreturn void print_help(FILE *restrict out)
Справка по ключамPrint help info. This long message is split into several pieces to help translators be able to align different blocks and identify the various pieces.
Referenced by main.
static void print_version(void)
Выводит информацию о справкеPrint version and copyright information.
Referenced by main.
static void print_simbols(const char *)
Вывод строки в верхнем регистре
Referenced by main.
static void gtk_greeting(const char *greeting_msg)
Используя GTK выводит сообение в отдельном окне
Referenced by main.
int main(int argc, char *argv[])
References print_version, print_help, gtk_greeting, print_simbols.